create table changes_the_abundance_of_by_food
(
    food_name       longtext               not null,
    microbiota_name longtext               not null,
    relationship    varchar(32) default '' not null
)collate = utf8mb4_bin;

INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Prevotella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Enterococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Streptococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Alistipes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Barnesiella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Ruminiclostridium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic diet', 'Cronobacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fermented soymilk', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fermented soymilk', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fermented soymilk', 'Porphyromonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fermented soymilk', 'Mogibacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fermented soymilk', 'Turicibacteraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Ruminococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Roseburia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Faecalibacterium prausnitzii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Prevotellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Akkermansia muciniphila', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Eubacterium rectale', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Roseburia faecis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('the recommended dietary intake of fibre and fat', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('the recommended dietary intake of fibre and fat', 'Bacteroidaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Faecalibacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Ruminococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Faecalibacterium prausnitzii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Coprococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Clostridiaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Veillonellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Oscillospira', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Bifidobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Phascolarctobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Dialister', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Coriobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Dorea', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Alcaligenaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Eubacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Eubacterium rectale', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Bifidobacterium sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Eubacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Eubacterium hallii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Coriobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Ruminococcus sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Roseburia sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic low carbohydrate high fat diet', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic low carbohydrate high fat diet', 'Faecalibacterium sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('ketogenic low carbohydrate high fat diet', 'Dorea sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('luten-free diet', 'Veillonellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('luten-free diet', 'Clostridiaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('luten-free diet', 'Coriobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('luten-free diet', 'Victivallaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('luten-free diet', 'Slackia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('luten-free diet', 'Ruminococcus bromii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('luten-free diet', 'ML615J.28', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('luten-free diet', 'Roseburia faecis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Parabacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Clostridium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Sutterella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Megamonas', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Paraprevotella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble corn fiber', 'Clostridiaceae SMB53', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('red wine', 'Veillonella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('red wine', 'Slackia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('red wine', 'Gordonibacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('red wine', 'Oscillatoria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('red wine', 'Oenococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary resistant starch type 4', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary resistant starch type 4', 'Ruminococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary resistant starch type 4', 'Parabacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary resistant starch type 4', 'Blautia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary resistant starch type 4', 'Oscillospira', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary resistant starch type 4', 'Eubacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary resistant starch type 4', 'Christensenella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('phenolic compounds from red wine and coffee', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('phenolic compounds from red wine and coffee', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('phenolic compounds from red wine and coffee', 'Clostridium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('phenolic compounds from red wine and coffee', 'Lactococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('probiotic fermented milk', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free diet', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free diet', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('yogurt', 'Enterobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('yogurt', 'Lactobacillus delbrueckii subsp. bulgaricus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('carbohydrates', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lupin kernel fiber', 'Bifidobacterium sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lupin kernel fiber', 'Erysipelatoclostridium ramosum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lupin kernel fiber', 'Clostridium spiroforme', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lupin kernel fiber', 'Clostridium cocleatum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sea buckthorn protein', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sea buckthorn protein', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sea buckthorn protein', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sea buckthorn protein', 'Clostridium coccoides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('barley', 'Prevotella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('barley', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high caloric diet', 'Bacteroidaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high caloric diet', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high caloric diet', 'Peptostreptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high caloric diet', 'Erysipelotrichaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('Pectic oligosaccharide', 'Bifidobacterium sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('Pectic oligosaccharide', 'Lactobacillus sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('Pectic oligosaccharide', 'Roseburia sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('Pectic oligosaccharide', 'Akkermansia sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('Pectic oligosaccharide', 'Bifidobacterium animalis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from tapioca', 'Incertae sedis XIV', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from tapioca', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from tapioca', 'Ruminococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from tapioca', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from corn', 'Porphyromonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from corn', 'Prevotellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from corn', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from corn', 'Incertae sedis XIV', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from corn', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('soluble fiber dextrin from corn', 'Ruminococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('corn-derived hydroxypropylated new resistant starch', 'Prevotellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('corn-derived hydroxypropylated new resistant starch', 'Incertae sedis XIV', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('corn-derived hydroxypropylated new resistant starch', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('promitor soluble corn fiber 70', 'Porphyromonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('promitor soluble corn fiber 70', 'Prevotellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Rikenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Clostridiales', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Ruminococcus gnavus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Peptoniphilus coxii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Caloramator mitchellensis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Lactobacillus hayakitensis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Lactobacillus intermedius', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Lactobacillus siliginis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Lactobacillus equi', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Peptoniphilus methioninivorax', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Trichodesmium hildebrandtii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Hydrocarboniphaga daqingensis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Polaribacter butkevichii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Pedobacter kwangyangensis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('acidic pH water', 'Flavobacterium antarcticum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary trans-10,cis-12-conjugated linoleic acid', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary trans-10,cis-12-conjugated linoleic acid', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary trans-10,cis-12-conjugated linoleic acid', 'Desulfovibrionaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary trans-10,cis-12-conjugated linoleic acid', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary trans-10,cis-12-conjugated linoleic acid', 'Peptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary trans-10,cis-12-conjugated linoleic acid', 'Porphyromonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary trans-10,cis-12-conjugated linoleic acid', 'Family XIII Incertae Sedis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('whole grain oat flour', 'Lactobacillales', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('whole grain oat flour', 'Prevotellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('whole grain oat flour', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('whole grain oat flour', 'Alcaligenaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('whole grain oat flour', 'Clostridiaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('whole grain oat flour', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('polysaccharides from the ink of Ommastrephes bartrami', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('polysaccharides from the ink of Ommastrephes bartrami', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('cranberry extract', 'Verrucomicrobia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('cranberry extract', 'Akkermansia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free diet', 'Verrucomicrobia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free diet', 'TM7', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free diet', 'Cyanobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free diet', 'Deferribacteres', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('milk', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('milk', 'Streptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('milk containing Lactobacillus casei BL23', 'Porphyromonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('milk containing Lactobacillus casei BL23', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('milk containing Lactobacillus casei BL23', 'Comamonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-containing chow', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-containing chow', 'Tannerella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-containing chow', 'Barnesiella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('gluten-free chow', 'Akkermansia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Ruminococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Rikenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('nutrition rodent diet 76', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('nutrition rodent diet 76', 'Alphaproteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('nutrition rodent diet 76', 'Gammaproteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('tekland rodent diet 8604', 'Lactobacillales', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Verrucomicrobia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'TM7', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Oscillibacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Allobaculum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Turicibacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('resistant starch', 'Oscillibacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('cocoa', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('cocoa', 'Staphylococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('cocoa', 'Clostridium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary polysaccharide from enteromorpha clathrata', 'Bifidobacterium sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary polysaccharide from enteromorpha clathrata', 'Akkermansia muciniphila', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary polysaccharide from enteromorpha clathrata', 'Lactobacillus sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('phycocyanin', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('phycocyanin', 'Ruminococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fasting mimicking diet', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fasting mimicking diet', 'Tenericutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fasting mimicking diet', 'Opisthokonta', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('fasting mimicking diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('refined olive oil', 'Desulfovibrionaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('refined olive oil', 'Spiroplasmataceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('refined olive oil', 'Helicobacteraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mulberry', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mulberry', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mulberry', 'Helicobacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mulberry', 'Prevotellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary supplementation with strawberry', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('coconut versus soy oil', 'Allobaculum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('coconut versus soy oil', 'Anaerofustis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('coconut versus soy oil', 'Lactobacillus reuteri', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('coconut versus soy oil', 'Deltaproteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('coconut versus soy oil', 'Akkermansia muciniphila', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('perilla oil', 'Alistipes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('perilla oil', 'Alloprevotella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('perilla oil', 'Parabacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('perilla oil', 'Rikenella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('perilla oil', 'Blautia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('perilla oil', 'Angelakisella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('perilla oil', 'Desulfovibrio', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('perilla oil', 'Bilophila', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('quinoa whole grain diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('quinoa whole grain diet', 'Escherichia/Shigella sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('quinoa whole grain diet', 'Peptoclostridium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('galactoglucomannan-rich hemicellulose extract in the diet', 'Odoribacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('galactoglucomannan-rich hemicellulose extract in the diet', 'Clostridiaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('galactoglucomannan-rich hemicellulose extract in the diet', 'Bacteroides uniformis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-salt diet', 'Erwinia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-salt diet', 'Christensenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-salt diet', 'Corynebacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-salt diet', 'Anaerostipes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oil tea', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('industrial trans-fatty acids-enriched diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('industrial trans-fatty acids-enriched diet', 'Desulfovibrionaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('industrial trans-fatty acids-enriched diet', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('industrial trans-fatty acids-enriched diet', 'Bacteroidales', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('industrial trans-fatty acids-enriched diet', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Erysipelotrichaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Porphyromonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Ruminococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Desulfovibrionaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Helicobacteraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Veillonellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary polyacetylenes falcarinol and falcarindiol', 'Lactobacillus reuteri', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary polyacetylenes falcarinol and falcarindiol', 'Turicibacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Deferribacteres', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Parabacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Rikenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Butyricimonas', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Prevotella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Mucispirillum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Candidatus Arthromitus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Erysipelotrichaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Allobaculum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Desulfovibrionaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Adlercreutzia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Clostridiaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Coprococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Dorea', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water', 'Ruminococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Cyanobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('proanthocyanidin-rich grape seed extract', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('proanthocyanidin-rich grape seed extract', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Akkermansia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('western diet', 'Dorea', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('galactooligosaccharide-rich diet', 'Alloprevotella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('galactooligosaccharide-rich diet', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('galactooligosaccharide-rich diet', 'Parasutterella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('galactooligosaccharide-rich diet', 'Coprococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('galactooligosaccharide-rich diet', 'Odoribacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Enterobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Carnobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Corynebacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Bifidobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Rikenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Clostridiaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Cryomorphaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Moraxellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Micrococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Bacteroidaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Prevotellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Coriobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('sugar', 'Pseudomonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Erysipelotrichaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Enterobacteriaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Clostridiaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Peptostreptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Blautia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Escherichia/Shigella sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Clostridium cluster XVIII', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Clostridium IV', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Flavonifractor', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Lasius', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Holdemania', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Peptostreptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Anaerotruncus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Clostridium cluster XIVb', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('short-term vegetarian and inulin-supplemented diet', 'Dorea', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Cyanobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Verrucomicrobia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Verrucomicrobia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Verrucomicrobiaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Bacteroidaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Muribaculaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Akkermansia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Oscillospira', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Ruminococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Akkermansia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('bamboo shoot fiber', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Corynebacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Rikenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Acinetobacter johnsonii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Streptophyta', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Ammoniphilus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Bacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Propionibacterium acnes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Bacteroides ovatus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Bilophila', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Sutterella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Parabacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Bifidobacterium longum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Akkermansia muciniphila', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'F16', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high phenolics rutgers scarlet lettuce', 'Roseburia sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high phenolics rutgers scarlet lettuce', 'Ruminococcus sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high phenolics rutgers scarlet lettuce', 'Peptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high phenolics rutgers scarlet lettuce', 'Coprococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high phenolics rutgers scarlet lettuce', 'Blautia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high phenolics rutgers scarlet lettuce', 'Clostridium sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Armatimonadetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Proteobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Cyanobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Planctomycetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Chlamydia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Oscillospira', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Pseudomonas', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Congregibacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Candidatus Endobugula', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Phaeobacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Clostridium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Escherichia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Helicobacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('oligofructose-maltodextrin', 'Adlercreutzia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Lactococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('high-fat diet', 'Streptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mango', 'Bifidobacterium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mango', 'Akkermansia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mango', 'Ruminococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mango', 'unclassified Bifidobacteria', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('mango', 'unclassified Akkermansia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary fiber', 'Bacteroidaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary fiber', 'Muribaculaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary fiber', 'Erysipelotrichaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary fiber', 'Alcaligenaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary fiber', 'Rikenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary fiber', 'Deferribacteraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary fiber', 'Desulfovibrionaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Muribaculaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Parabacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Odoribacter', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Akkermansia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Ruminococcus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Oscillospira', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Lactobacillaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Prevotellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Bacteroidaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Allobaculum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Lachnospiraceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Blautia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('meat protein', 'Lactobacillus', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('heat-treated high-fat diet', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('heat-treated high-fat diet', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('heat-treated high-fat diet', 'Mucispirillum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('heat-treated high-fat diet', 'unclassified Clostridiales', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('heat-treated high-fat diet', 'Muribaculaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('heat-treated high-fat diet', 'unclassified Rikenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('heat-treated high-fat diet', 'Allobaculum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Bacteroidetes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Bacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Parabacteroides', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Clostridium', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Mucispirillum', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('lingonberry', 'Oscillospira', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Firmicutes', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Verrucomicrobia', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Clostridium baratii', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Erysipelotrichaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Peptostreptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Streptococcaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Muribaculaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Prevotella sp.', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Rikenellaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Porphyromonadaceae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Bacteroides caccae', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Bacteroides uniformis', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Sutterella', 'changes_the_abundance_of_by_food');
INSERT INTO relationship.changes_the_abundance_of_by_food (food_name, microbiota_name, relationship) VALUES ('dietary flaxseed', 'Akkermansia muciniphila', 'changes_the_abundance_of_by_food');