create table metabolite
(
    metabolite_name longtext not null,
    pubchem_id      longtext not null,
    hmdb_id         longtext not null,
    chebi_id        longtext not null
)collate = utf8mb4_bin;

INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Acetate', '175', 'null', 'CHEBI:30089');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Butyrate', '104775', 'null', 'CHEBI:17968');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Luteolin', '5280445', 'HMDB0005800', 'CHEBI:15864');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Deoxycholic acid', '222528', 'HMDB0000626', 'CHEBI:28834');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Lithocholic acid', '9903', 'HMDB0000761', 'CHEBI:16325');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4S)-4-[(2E)-Oct-2-enoyloxy]-4-(trimethylazaniumyl)butanoate', '53481667', 'null', 'CHEBI:176711');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Bile acid', '439520', 'null', 'CHEBI:22868');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Propionate', '104745', 'null', 'CHEBI:17272');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phenolic acid', 'null', 'null', 'CHEBI:166890');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Kaempferol-3-sorphoroside', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3,4-Dihydroxyphenylacetic acid', '547', 'HMDB0001336', 'CHEBI:41941');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dihydrocaffeic acid', '348154', 'HMDB0000423', 'CHEBI:48400');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4-Hydroxyphenylacetic acid', '127', 'HMDB0000020', 'CHEBI:18101');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-(4-Hydroxyphenyl)propionic acid', '10394', 'HMDB0002199', 'CHEBI:32980');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phloroglucinol', '359', 'HMDB0013675', 'CHEBI:16204');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Indoxyl sulfate', '10258', 'HMDB0000682', 'CHEBI:43355');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('p-Cresol sulfate', '4615423', 'HMDB0011635', 'CHEBI:82914');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phenylacetylglutamine', '92258', 'HMDB0006344', 'CHEBI:17884');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dihydrodaidzein', '176907', 'HMDB0005760', 'CHEBI:75842');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Equol', '91469', 'HMDB0002209', 'CHEBI:34741');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2,3-Butanediol', '262', 'HMDB0003156', 'CHEBI:62064');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-Acetoxypropanoic acid', '79041', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Acetoin', '179', 'HMDB0003243', 'CHEBI:15688');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2,3-Butanedione', '650', 'HMDB0003407', 'CHEBI:16583');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Trimethylamine', '1146', 'HMDB0000906', 'CHEBI:18139');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-Hydroxy-4-methoxybenzenepropanoic acid', '2752054', 'HMDB0131138', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Hesperetin dihydrochalcone', '147608', 'HMDB0128062', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Succinate', '160419', 'null', 'CHEBI:30031');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('O-Desmethylangolensin', '89472', 'HMDB0004629', 'CHEBI:88902');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-(3,4-Dihydroxyphenyl)-3-(2,4,6-trihydroxyphenyl)-2-propanol', '21722175', 'HMDB0127722', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3,4-diHPP-2-ol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3,4-diHPVL', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Trimethylamine oxide', '1145', 'HMDB0000925', 'CHEBI:15724');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('D-Lactic acid', '61503', 'HMDB0001311', 'CHEBI:42111');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-Indolepropionic acid', '3744', 'HMDB0002302', 'CHEBI:43580');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Caffeic acid', '689043', 'HMDB0001964', 'CHEBI:16433');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-(3-Hydroxyphenyl)propanoic acid', '91', 'HMDB0000375', 'CHEBI:1427');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dehydroxychlorogenic acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dihydrochlorogenic acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2,3-Dihydroxypropyl (E)-3-(3,4-dihydroxyphenyl)prop-2-enoate', '5315606', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dihydrocaffeoyl-glycerol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-Hydroxyphenethyl alcohol', '83404', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phenylacetic acid', '999', 'HMDB0000209', 'CHEBI:30745');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Isoquercitrin', '5280804', 'HMDB0037362', 'CHEBI:68352');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('5-OH-Equol', '9795113', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-(4-Hydroxyphenyl)propionic acid, (2S)-', '6971268', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('8-Prenylnaringenin', '480764', 'null', 'CHEBI:50207');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Alanine', '5950', 'HMDB0062251', 'CHEBI:16977');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Leucine', '6106', 'HMDB0000687', 'CHEBI:15603');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('l-Isoleucine', '6306', 'HMDB0000172', 'CHEBI:17191');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Glycine', '750', 'HMDB0000123', 'CHEBI:15428');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Proline', '145742', 'HMDB0000162', 'CHEBI:17203');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Serine', '5951', 'HMDB0000187', 'CHEBI:17115');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-Hydroxybenzoic acid', '7420', 'HMDB0002466', 'CHEBI:30764');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4-Hydroxybenzoic acid', '135', 'HMDB0000500', 'CHEBI:30763');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Sedoheptulose', '5459879', 'null', 'CHEBI:16802');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Citric acid', '311', 'HMDB0000094', 'CHEBI:30769');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Tricarballylic acid', '14925', 'HMDB0031193', 'CHEBI:45969');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Pipecolic acid', '849', 'HMDB0000070', 'CHEBI:17964');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Malic acid', '525', 'null', 'CHEBI:6650');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Tartaric acid', '875', 'HMDB0062642', 'CHEBI:15674');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Creatine', '586', 'HMDB0000064', 'CHEBI:16919');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-Imino-1-methylimidazolidin-4-one', '588', 'HMDB0000562', 'CHEBI:16737');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Glycocholic acid', '10140', 'HMDB0000138', 'CHEBI:17687');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-Phenylpropionic acid', '107', 'HMDB0000764', 'CHEBI:28631');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4-Pyridoxic acid', '6723', 'HMDB0000017', 'CHEBI:17405');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Enterodiol', '115089', 'HMDB0005056', 'CHEBI:81556');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Aglycone', 'null', 'null', 'CHEBI:166892');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(2R)-1-(3,4-dihydroxyphenyl)-3-(2,4,6-trihydroxyphenyl)-propan-2-ol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(2R)-1-(3-hydroxyphenyl)-3-(2,4,6-trihydroxyphenyl)propan-2-ol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Lactate', '91435', 'null', 'CHEBI:24996');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Daidzein', '5281708', 'HMDB0003312', 'CHEBI:28197');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Levodopa', '6047', 'HMDB0000181', 'CHEBI:15765');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Sulfate', '1117', 'HMDB0001448', 'CHEBI:16189');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Baohuoside I', '5488822', 'null', 'CHEBI:82619');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Icaritin', '5318980', 'HMDB0139407', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Formate', '283', 'null', 'CHEBI:15740');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('L-Lactate', '5460161', 'null', 'CHEBI:16651');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Ethanol', '702', 'HMDB0000108', 'CHEBI:16236');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Platycodin D', '162859', 'null', 'CHEBI:70436');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Chrysin', '5281607', 'HMDB0036619', 'CHEBI:75095');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Apigenin', '5280443', 'HMDB0002124', 'CHEBI:18388');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3,9-Dihydroxybenzo[c]chromen-6-one', '10376459', 'HMDB0142418', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Pyruvate', '107735', 'null', 'CHEBI:15361');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Acetyl phosphate(2-)', '4183249', 'null', 'CHEBI:22191');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-Methyloxindole', '150923', 'null', 'CHEBI:17397');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('5-Hydroxyindole-3-acetic acid', '1826', 'HMDB0000763', 'CHEBI:27823');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Indole-3-acrylic acid', '5375048', 'HMDB0000734', 'CHEBI:132244');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Indole-3-carboxylic acid', '69867', 'HMDB0003320', 'CHEBI:24809');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Indole', '798', 'HMDB0000738', 'CHEBI:16881');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Oxindole', '321710', 'HMDB0061918', 'CHEBI:31697');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-Methylindole', '6736', 'HMDB0000466', 'CHEBI:9171');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Kynurenic acid', '3845', 'HMDB0000715', 'CHEBI:18344');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Histidine', '6274', 'HMDB0000177', 'CHEBI:15971');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('L-Cysteine', '5862', 'HMDB0000574', 'CHEBI:17561');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Cystine', '595', 'null', 'CHEBI:17376');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Glutathione', '124886', 'HMDB0000125', 'CHEBI:16856');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Asparagine', '6267', 'HMDB0000168', 'CHEBI:17196');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('DL-Alanine', '602', 'HMDB0062251', 'CHEBI:16449');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-Hydroxy-3-(5-hydroxy-1H-indol-3-yl)propanoic acid', '192215', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Indole-3-lactic acid', '92904', 'null', 'CHEBI:24813');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-Hydroxy-3-(4-hydroxyphenyl)propanoic acid', '9378', 'HMDB0000755', 'CHEBI:17385');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-(3,4-Dihydroxyphenyl)-2-hydroxypropanoic acid', '439435', 'HMDB0003503', 'CHEBI:17807');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Nicotinic acid', '938', 'HMDB0001488', 'CHEBI:15940');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(R)-3-Hydroxybutyrate', '6971058', 'HMDB0000011', 'CHEBI:10983');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Acifran', '51576', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(S)-3-Hydroxybutyric acid', '94318', 'HMDB0000442', 'CHEBI:17290');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Sodium 3-hydroxybutyrate', '23676771', 'null', 'CHEBI:113373');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Diosmetin', '5281612', 'HMDB0029676', 'CHEBI:4630');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Acacetin', '5280442', 'null', 'CHEBI:15335');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Valerate', '114781', 'null', 'CHEBI:31011');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Taurocholic acid', '6675', 'HMDB0000036', 'CHEBI:28865');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dihydroresveratrol', '185914', 'HMDB0240498', 'CHEBI:4582');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Lunularin', '181511', 'null', 'CHEBI:6568');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3,4-Dihydroxy-trans-stilbene', '10176710', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-(3-Chloro-2,6-dihydroxy-4-methoxyphenyl)-1-hexanone', '3081033', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Colibactin', '138805674', 'null', 'CHEBI:156303');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('beta-D-Fructofuranose', '439709', 'null', 'CHEBI:28645');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Genistein', '5280961', 'HMDB0003217', 'CHEBI:28088');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dihydrogenistein', '9838356', 'HMDB0005897', 'CHEBI:34707');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('D-Mannose', '18950', 'HMDB0000169', 'CHEBI:4208');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2,2'',4,4''-Tetrabromodiphenyl ether', '95170', 'HMDB0037547', 'CHEBI:81584');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2,2'',4,4'',5-Pentabromodiphenyl ether', '36159', 'HMDB0037516', 'CHEBI:81582');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(10-[(Acetyloxy)methyl]-9-anthryl)methyl acetate', '613145', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Isovaleric acid', '10430', 'HMDB0000718', 'CHEBI:28484');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Palmitic acid', '985', 'HMDB0000220', 'CHEBI:15756');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('D-Glucuronic Acid', '94715', 'HMDB0000127', 'CHEBI:42717');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Tretinoin', '444795', 'null', 'CHEBI:15367');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('10-Keto-12Z-octadecenoic acid', '24970825', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Pioglitazone', '4829', 'HMDB0015264', 'CHEBI:8228');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Hydroxyquercitrin', '129887767', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Quercetin', '5280343', 'HMDB0005794', 'CHEBI:16243');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3,4-Dihydroxybenzoic acid', '72', 'HMDB0001856', 'CHEBI:36062');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Vancomycin', '14969', 'HMDB0014653', 'CHEBI:28001');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Diosgenin', '99474', 'null', 'CHEBI:4629');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Hydroquinone', '785', 'HMDB0002434', 'CHEBI:17594');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('6,7,4''-Trihydroxyisoflavone', '5284649', 'HMDB0031715', 'CHEBI:74957');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('5-(3,4-Dihydroxyphenyl)-valerolactone', '45093073', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4-Hydroxy-(3'',4''-dihydroxyphenyl)-valeric acid', '52920332', 'HMDB0041679', 'CHEBI:137478');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Folic acid', '135398658', 'HMDB0000121', 'CHEBI:27470');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dihydroglycitein', '101101166', 'null', 'CHEBI:174736');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Quinic acid', '6508', 'HMDB0003072', 'CHEBI:17521');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Oxalacetic acid', '970', 'HMDB0000223', 'CHEBI:30744');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Norathyriol', '5281656', 'null', 'CHEBI:7622');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Serotonin', '5202', 'HMDB0000259', 'CHEBI:28790');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Leucocianidol', '71629', 'null', 'CHEBI:15758');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Glycerol', '753', 'HMDB0000131', 'CHEBI:17754');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Genipin', '442424', 'HMDB0035830', 'CHEBI:5298');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Indole-3-carboxaldehyde', '10256', 'HMDB0029737', 'CHEBI:28238');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('10-Oxo-11-octadecenoic acid', '10308378', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Ponciretin', '25201019', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Lacto-N-tetraose', '440993', 'HMDB0006566', 'CHEBI:30248');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('beta-D-Gal-(1->4)-beta-D-GlcNAc-(1->3)-beta-D-Gal-(1->4)-D-Glc', '9831622', 'HMDB0006567', 'CHEBI:60239');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2,4-Dioxopentanedioic acid', '444873', 'null', 'CHEBI:42056');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('6''-Hydroxy-O-desmethylangolensin', '20601635', 'HMDB0041695', 'CHEBI:88662');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-(2,4-Dihydroxyphenyl)propanoic acid', '96384', 'HMDB0126386', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1,3-Diphenylpropan-2-ol', '138478', 'HMDB0135544', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-Piperazinepentanamide, N-((1S,2R)-2,3-dihydro-2-hydroxy-1H-inden-1-yl)-2-(((1,1-dimethylethyl)amino)carbonyl)-4-(furo(2,3-b)pyridin-5-ylmethyl)-gamma-hydroxy-alpha-(phenylmethyl)-, (alphaR,gammaS,2S)-', '5481990', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dopamine', '681', 'HMDB0000073', 'CHEBI:18243');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-Amino-1-methyl-6-phenylimidazo[4,5-b]pyridine', '1530', 'null', 'CHEBI:76290');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('7-Hydroxy-5-methyl-3-phenyl-6,7,8,9-tetrahydropyrido[3'',2'':4,5]imidazo[1,2-a]pyrimidin-5-ium chloride', '129849310', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Quercitrin', '5280459', 'HMDB0033751', 'CHEBI:17558');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Urolithin A', '5488186', 'HMDB0013695', 'CHEBI:168442');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(2S)-1-(3-hydroxyphenyl)-3-(2,4,6-trihydroxyphenyl)propan-2-ol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Ginsenoside-Rd', '24721561', 'HMDB0035778', 'CHEBI:67988');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Loganetin', '10466307', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Arctigenin', '64981', 'null', 'CHEBI:79');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Ursodeoxycholic acid', '31401', 'HMDB0000946', 'CHEBI:9907');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phenylalanine', '6140', 'HMDB0000159', 'CHEBI:17295');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Glutamic acid', '33032', 'HMDB0000148', 'CHEBI:16015');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('L-Threonine', '6288', 'HMDB0000167', 'CHEBI:16857');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Glycitein', '5317750', 'HMDB0005781', 'CHEBI:34778');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Kaempferol', '5280863', 'HMDB0005801', 'CHEBI:28499');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('5-Hydroxy-1H-imidazole-4-carboxamide', '124343', 'null', 'CHEBI:88290');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Ginsenoside Rh2', '119307', 'null', 'CHEBI:77147');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(20S)-Protopanaxadiol', '11213350', 'null', 'CHEBI:75950');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('20(R)-Ginsenoside Rh2', '54580480', 'null', 'CHEBI:172776');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Protopanaxadiol', '9920281', 'null', 'CHEBI:76237');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3''-desmethylarctigenin', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Glycerophospholipids', 'null', 'null', 'CHEBI:37739');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Propanol', '1031', 'null', 'CHEBI:28831');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Ethyl phenyllactate, (-)-', '9877619', ' HMDB0032618', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(R)-3-(4-Hydroxyphenyl)lactate', '9548632', 'null', 'CHEBI:10980');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Quercimeritrin', '5282160', 'null', 'CHEBI:28529');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('11-Methoxycurvularin', '10381440', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Hydrogen', '783', 'HMDB0001362', 'CHEBI:18276');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Isobutyric acid', '6590', 'HMDB0001873', 'CHEBI:16135');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(2S)-1-(3,4-dihydroxyphenyl)-3-(2,4,6-trihydroxyphenyl) propan-2-ol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4R)-4-hydroxy-5-(3,4-dihydroxyphenyl) valeric acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4R)-5-(3,4-dihydroxyphenyl)-γ-valerolactone', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4S)-4-hydroxy-5-(3,4-dihydroxyphenyl) valeric acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4S)-5-(3,4-dihydroxyphenyl)-γ-valerolactone', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4R)-4-hydroxy-5-(3-hydroxyphenyl) valeric acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4S)-4-hydroxy-5-(3-hydroxyphenyl) valeric acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4R)-5-(3-hydroxyphenyl)-γ-valerolactone', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(4S)-5-(3-hydroxyphenyl)-γ-valerolactone', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Myricetin', '5281672', 'HMDB0002755', 'CHEBI:18152');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Quercetin', '5280343', 'HMDB0033751', 'CHEBI:16243');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('type I collagen cross-linked c-telopeptide', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('procollagen type 1 n-terminal propeptide', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('p-Cresol glucuronide', '154035', 'HMDB0011686', 'CHEBI:87986');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Baicalein', '5281605', 'null', 'CHEBI:2979');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Baicalin', '64982', 'HMDB0041832', 'CHEBI:2981');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Secoisolariciresinol', '65373', 'HMDB0013692', 'CHEBI:65004');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Lariciresinol', '332427', 'null', 'CHEBI:67246');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2,3-Bis(3,4-dihydroxybenzyl)butyrolactone', '500189', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Naringenin chalcone', '5280960', 'HMDB0029631', 'CHEBI:15413');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phloretin', '4788', 'HMDB0003306', 'CHEBI:17276');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('5,7-Dihydroxy-2-(4-hydroxyphenyl)chroman-4-one', '932', 'HMDB0128074', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Cholic acid', '221493', 'HMDB0000619', 'CHEBI:16359');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Eicosapentaenoic acid', '446284', 'HMDB0001999', 'CHEBI:28364');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Chenodeoxycholic acid', '10133', 'HMDB0000518', 'CHEBI:16755');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Desoxycortone', '6166', 'HMDB0000016', 'CHEBI:16973');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('7-Dehydrocholesterol', '439423', 'HMDB0000032', 'CHEBI:17759');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Retinol', '445354', 'HMDB0000305', 'CHEBI:17336');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Myristic acid', '11005', 'HMDB0000806', 'CHEBI:28875');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Benzoic acid', '243', 'HMDB0001870', 'CHEBI:30746');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Indole-3-acetic acid', '802', 'HMDB0000197', 'CHEBI:16411');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4''-dehydroxylated (�?-epigallocatechin', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-(3,4,5-trihydroxyphenyl)-3-(2,4,6trihydroxyphenyl)propan-2-ol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-(3,5-dihydroxyphenyl)-3-(2,4,6-trihydroxyphenyl)propan-2-ol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4''-dehydroxylated isomer (�?-gallocatechin', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phenyalanine', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Indole-3-pyruvic acid', '803', 'HMDB0060484', 'CHEBI:29750');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-Methylindole', '11781', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phenylpyruvic acid', '997', 'HMDB0000205', 'CHEBI:30851');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Atrolactic acid', '1303', 'HMDB0142137', 'CHEBI:50392');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Tyramine', '5610', 'HMDB0000306', 'CHEBI:15760');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Valine', '6287', 'HMDB0000883', 'CHEBI:16414');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-Hydroxy-2-methylbutanenitrile', '97823', 'null', 'CHEBI:60954');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('N-Acetylputrescine', '122356', 'HMDB0002064', 'CHEBI:17768');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Betonicine', '164642', 'HMDB0029412', 'CHEBI:85533');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('N-Acetyl-D-Mannosamine', '439281', 'null', 'CHEBI:63153');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-Formaminobenzoylacetate', '440807', 'null', 'CHEBI:1098');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('12-Ketolithocholic acid', '3080612', 'HMDB0000328', 'CHEBI:139134');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Hyocholate', '92805', 'null', 'CHEBI:133661');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Hypoxanthine', '135398638', 'HMDB0000157', 'CHEBI:17368');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4-Acetamidobutyric acid', '18189', 'HMDB0003681', 'CHEBI:17645');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('N(6)-Methyllysine', '164795', 'HMDB0002038', 'CHEBI:17604');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('N-Isovaleroylglycine', '546304', 'HMDB0000678', 'CHEBI:70984');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('21H-Biline-8,12-dipropanoic acid, 3,18-diethyl-1,4,5,15,16,19,22,24-octahydro-2,7,13,17-tetramethyl-1,19-dioxo-', '6433298', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Murideoxycholate', '21158657', 'null', 'CHEBI:58876');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Pentahomomethionine', '25010767', 'null', 'CHEBI:50713');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('7-Hydroxy-3-oxocholanoic acid', '53477692', 'HMDB0000460', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Nutriadeoxycholate vulpecholate', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('7a-hydroxy-3-oxo-5b-cholanoate', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Valyl-Hydroxyproline', '10242944', 'HMDB0029128', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-Methoxypyrene', '160236', 'HMDB0060324', 'CHEBI:81610');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Valyl-Hydroxyproline', '10242944', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Isovanillic acid 3-O-sulfate', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Phenyl sulfate', '18795569', 'null', 'CHEBI:85289');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('gamma-Aminobutyric acid', '119', 'HMDB0000112', 'CHEBI:16865');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Purine', '1044', 'HMDB0001366', 'CHEBI:17258');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Uric acid', '1175', 'HMDB0000289', 'CHEBI:17775');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Rheinanthrone', '119396', 'HMDB0039449', 'CHEBI:174546');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('GDP-L-fucose', '135412609', 'HMDB0001095', 'CHEBI:17009');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Oxiglutatione', '65359', 'HMDB0003337', 'CHEBI:17858');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Cysteine-glutathione disulfide', '3080690', 'HMDB0000656', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Taurine', '1123', 'HMDB0000251', 'CHEBI:15891');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Histamine', '774', 'HMDB0000870', 'CHEBI:18295');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('(Z)-10-Hydroxy-12-octadecenoic acid', '46186046', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Methanol, (methyl-ONN-azoxy)-', '11554', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Cyanuric acid', '7956', 'HMDB0041861', 'CHEBI:38028');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-Phenyl-1,2-propanedione', '11363', 'HMDB0035243', 'CHEBI:63552');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2-Oxoglutaric acid', '51', 'HMDB0000208', 'CHEBI:30915');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3-(4-Hydroxy-3-methoxyphenyl)propionic acid', '14340', 'HMDB0062121', 'CHEBI:86612');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('2,8-Quinolinediol', '97250', 'HMDB0240311', 'CHEBI:17715');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Ergothioneine', '5351619', 'HMDB0003045', 'CHEBI:4828');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('7-Ketodeoxycholic acid', '188292', 'HMDB0000391', 'CHEBI:16390');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Isorhamnetin', '5281654', 'HMDB0002655', 'CHEBI:6052');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Lysophosphatidylethanolamine', '73755142', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4''-Hydroxy-3'',5,6,7,8-pentamethoxyflavone', '21593928', 'HMDB0029547', 'CHEBI:175929');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('4-Hydroxy-5-(3-hydroxyphenyl)valeric acid', '52920334', 'null', 'CHEBI:137492');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Epigallocatechin', '72277', 'null', 'CHEBI:42255');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Gallic acid', '370', 'HMDB0005807', 'CHEBI:30778');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Sclerotioramine', '135860757', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Sclerotiorin', '6436015', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1,4-Diaminobutane', '1045', 'HMDB0001414', 'CHEBI:17148');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Spermidine', '1102', 'HMDB0001257', 'CHEBI:16610');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Acetylcholine', '187', 'HMDB0000895', 'CHEBI:15355');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Estradiol', '5757', 'HMDB0000151', 'CHEBI:16469');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3,3-Dimethyl-1-butanol', '12233', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Lipoteichoic acid', '137349712', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Dinoprostone', '5280360', 'null', 'CHEBI:15551');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('N,N,N-trimethyl-5-aminovaleric acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('3,8,9-Trihydroxy-6H-benzo[c]chromen-6-one', '60198001', 'null', 'CHEBI:174255');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('5-Acetamido-2-azaniumylpentanoate', '121596237', 'null', 'CHEBI:133180');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('11-oxo-mogrol', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('13-hydroxy-9(Z),15(Z)-octadecadienoic acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('13-oxo-9(Z),15(Z)-octadecadienoic acid', 'null', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Nicotinamide', '936', 'null', 'CHEBI:17154');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Tryptamine', '1150', 'HMDB0000303', 'CHEBI:16765');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Oxyberberine', '11066', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('9,11-Octadecadienoic acid', '5282796', 'HMDB0005047', 'CHEBI:36025');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1D-Myo-inositol 6-phosphate', '161368', 'null', 'CHEBI:64838');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('[(1S,2R,3S,4S,5R,6S)-2,3,5-Trihydroxy-4,6-diphosphonooxycyclohexyl] dihydrogen phosphate', '55310', 'null', 'null');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1D-Myo-inositol 1,4,5,6-tetrakisphosphate(8-)', '25201642', 'HMDB0004527', 'CHEBI:57627');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('D-Glutamic acid', '23327', 'HMDB0003339', 'CHEBI:15966');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Sodium benzoate', '517055', 'HMDB0001870', 'CHEBI:113455');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Arachidonic acid', '444899', 'HMDB0001043', 'CHEBI:15843');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('7-Sulfocholic acid', '459070', 'HMDB0002421', 'CHEBI:166724');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Tryptophan', '6305', 'HMDB0000929', 'CHEBI:16828');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('L-Urobilin', '5280818', 'HMDB0240259', 'CHEBI:29023');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('1-Deoxynojirimycin', '29435', 'HMDB0035359', 'CHEBI:44369');
INSERT INTO gutmgene.metabolite (metabolite_name, pubchem_id, hmdb_id, chebi_id) VALUES ('Stachyose', '439531', 'HMDB0003553', 'CHEBI:17164');