create table drug
(
    name        longtext not null,
    drugbank_id longtext not null
)collate = utf8mb4_bin;

INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Synbiotic', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Arsenic', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Infliximab', 'DB00065');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Proton Pump Inhibitor', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Vitamin A', 'DB00162');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Iron', 'DB01592');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Propidium Monoazide', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Prebiotics', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Selective Serotonin Reuptake Inhibitor', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Antibiotic', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Prescr. antibiotic', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Acetaminophen', 'DB00316');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Opioid', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Metformin', 'DB00331');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Loop', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Insulin Aspart', 'DB01306');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Anticholinergic drug', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('H2 Antagonist', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Acetylsalicylic acid', 'DB00945');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Aromatase Inhibitor', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Antispasmodic drug', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Aminosalicylate', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Enrofloxacin', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Clarithromycin,Metronidazole', 'DB01211,DB00916');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('non-steroidal anti-inflammatory drug', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('advanced glycation end product', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Bifidobacteria', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Probiotic Lactobacillus paracasei CBA L74', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Polydextrose', 'DB14836');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('nonsteroidal anti-infammatory drug', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Probiotic Lactobacillus casei strain Shirota', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Yangyin Tiluo Decoction', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Probiotics', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Adalimumab', 'DB00051');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Rehmannia glutinosa root', 'DB14290');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Vitamin D3', 'DB00169');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Vitamin D', 'DB11094');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Acarbose', 'DB00284');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('broad-spectrum antibiotic', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Cocaine', 'DB00907');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Prebiotic inulin-type fructan', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('amoxicillin-clavulanate,Saccharomyces boulardii CNCM I-745', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Moutan Cortex and Paeoniae Radix Rubra', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('systemic antibiotic', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Saccharomyces boulardii', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('antiretroviral drug', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Ginseng polysaccharide', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Epigallocatechin gallate', 'DB12116');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Bifico', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('combination of quercetin and resveratrol', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Lactobacillus casei CCFM419', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Danshensu Bingpian Zhi', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Dextran sodium sulfate', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Saccharin', 'DB12418');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Bromochloromethane', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Propolis wax', 'DB11355');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Cadmium', 'DB14085');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Fructose', 'DB04173');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Inulin', 'DB00638');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Gynostemma pentaphyllum saponins', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Carbendazim', 'DB13009');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Trimellitic anhydride', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Lactobacillus casei variety rhamnosus', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Vancomycin', 'DB00512');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Berberine', 'DB04115');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Fructooligosaccharides', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Cyclophosphamide', 'DB00531');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Tigecycline', 'DB00560');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Fucosyllactose', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Qushi Huayu Fang', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('branched chain fatty acid', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Organophosphate diazinon', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Isoliquiritigenin', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Imazalil', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Vancomycin,Bacitracin', 'DB00512,DB00626');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Resveratrol', 'DB02709');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('YangZheng XiaoJi', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Rifaximin', 'DB01220');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Fructooligosaccharide', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('JinQi Jiangtang', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Porphyromonas gingivalis', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Green Macroalgae Enteromorpha Prolifera Polyphenol', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Green Seaweed Enteromorpha prolifera Flavonoid', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('rich-polyphenols extract of Dendrobium loddigesii', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Garcinol', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Codonopsis pilosula Nannf', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Lactobacillus acidophilus DDS-1', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('mixed lactic acid', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Diammonium Glycyrrhizinate', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('N-Acetylcysteine', 'DB06151');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('hydroxysafflor yellow A', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Polybrominated diphenyl ether', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Lactulose', 'DB00581');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Chitin Oligosaccharide', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Neoagarotetraose', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Catestatin', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Sodium butyrate', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Penicillin G,erythromycin', 'DB01053,DB00199');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Ampicillin', 'DB00415');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Probiotics and Garcinia cambogia extract', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('American Ginseng', 'DB14296');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Lactobacillus fermentum CRL1446', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('β-Glucans', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('chronic 2,3,7,8-tetrachlorodibenzo-p-dioxin', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('azithromycin,amoxicillin and cefaclor', 'DB00207,DB01060,DB00833');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Dextran sulfate sodium', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Nondigestible fructan', 'null');
INSERT INTO gutmdisorder.drug (name, drugbank_id) VALUES ('Lead', 'null');