create table food
(
    food_name longtext not null
)collate = utf8mb4_bin;

INSERT INTO gutmdisorder.food (food_name) VALUES ('ketogenic diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('fermented soymilk');
INSERT INTO gutmdisorder.food (food_name) VALUES ('resistant starch');
INSERT INTO gutmdisorder.food (food_name) VALUES ('the recommended dietary intake of fibre and fat');
INSERT INTO gutmdisorder.food (food_name) VALUES ('soluble corn fiber');
INSERT INTO gutmdisorder.food (food_name) VALUES ('ketogenic low carbohydrate high fat diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('luten-free diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('red wine');
INSERT INTO gutmdisorder.food (food_name) VALUES ('dietary resistant starch type 4');
INSERT INTO gutmdisorder.food (food_name) VALUES ('phenolic compounds from red wine and coffee');
INSERT INTO gutmdisorder.food (food_name) VALUES ('probiotic fermented milk');
INSERT INTO gutmdisorder.food (food_name) VALUES ('gluten-free diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('yogurt');
INSERT INTO gutmdisorder.food (food_name) VALUES ('carbohydrates');
INSERT INTO gutmdisorder.food (food_name) VALUES ('lupin kernel fiber');
INSERT INTO gutmdisorder.food (food_name) VALUES ('sea buckthorn protein');
INSERT INTO gutmdisorder.food (food_name) VALUES ('barley');
INSERT INTO gutmdisorder.food (food_name) VALUES ('high caloric diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('high-fat_diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('Pectic oligosaccharide');
INSERT INTO gutmdisorder.food (food_name) VALUES ('soluble fiber dextrin from tapioca');
INSERT INTO gutmdisorder.food (food_name) VALUES ('soluble fiber dextrin from corn');
INSERT INTO gutmdisorder.food (food_name) VALUES ('corn-derived hydroxypropylated new resistant starch');
INSERT INTO gutmdisorder.food (food_name) VALUES ('promitor soluble corn fiber 70');
INSERT INTO gutmdisorder.food (food_name) VALUES ('acidic pH water');
INSERT INTO gutmdisorder.food (food_name) VALUES ('dietary trans-10,cis-12-conjugated linoleic acid');
INSERT INTO gutmdisorder.food (food_name) VALUES ('whole grain oat flour');
INSERT INTO gutmdisorder.food (food_name) VALUES ('polysaccharides from the ink of Ommastrephes bartrami');
INSERT INTO gutmdisorder.food (food_name) VALUES ('cranberry extract');
INSERT INTO gutmdisorder.food (food_name) VALUES ('milk');
INSERT INTO gutmdisorder.food (food_name) VALUES ('milk containing Lactobacillus casei BL23');
INSERT INTO gutmdisorder.food (food_name) VALUES ('gluten-containing chow');
INSERT INTO gutmdisorder.food (food_name) VALUES ('gluten-free chow');
INSERT INTO gutmdisorder.food (food_name) VALUES ('nutrition rodent diet 76');
INSERT INTO gutmdisorder.food (food_name) VALUES ('tekland rodent diet 8604');
INSERT INTO gutmdisorder.food (food_name) VALUES ('cocoa');
INSERT INTO gutmdisorder.food (food_name) VALUES ('dietary polysaccharide from enteromorpha clathrata');
INSERT INTO gutmdisorder.food (food_name) VALUES ('phycocyanin');
INSERT INTO gutmdisorder.food (food_name) VALUES ('fasting mimicking diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('refined olive oil');
INSERT INTO gutmdisorder.food (food_name) VALUES ('mulberry');
INSERT INTO gutmdisorder.food (food_name) VALUES ('dietary supplementation with strawberry');
INSERT INTO gutmdisorder.food (food_name) VALUES ('coconut versus soy oil');
INSERT INTO gutmdisorder.food (food_name) VALUES ('perilla oil');
INSERT INTO gutmdisorder.food (food_name) VALUES ('quinoa whole grain diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('galactoglucomannan-rich hemicellulose extract in the diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('high-salt diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('oil tea');
INSERT INTO gutmdisorder.food (food_name) VALUES ('industrial trans-fatty acids-enriched diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('western diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('dietary polyacetylenes falcarinol and falcarindiol');
INSERT INTO gutmdisorder.food (food_name) VALUES ('molecular hydrogen-dissolved alkaline electrolyzed water');
INSERT INTO gutmdisorder.food (food_name) VALUES ('proanthocyanidin-rich grape seed extract');
INSERT INTO gutmdisorder.food (food_name) VALUES ('galactooligosaccharide-rich diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('sugar');
INSERT INTO gutmdisorder.food (food_name) VALUES ('short-term vegetarian and inulin-supplemented diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('bamboo shoot fiber');
INSERT INTO gutmdisorder.food (food_name) VALUES ('high phenolics rutgers scarlet lettuce');
INSERT INTO gutmdisorder.food (food_name) VALUES ('oligofructose-maltodextrin');
INSERT INTO gutmdisorder.food (food_name) VALUES ('mango');
INSERT INTO gutmdisorder.food (food_name) VALUES ('dietary fiber');
INSERT INTO gutmdisorder.food (food_name) VALUES ('lingonberry');
INSERT INTO gutmdisorder.food (food_name) VALUES ('meat protein');
INSERT INTO gutmdisorder.food (food_name) VALUES ('heat-treated high-fat diet');
INSERT INTO gutmdisorder.food (food_name) VALUES ('dietary flaxseed');