create table disorder
(
    name  longtext not null,
    do_id longtext not null
)collate = utf8mb4_bin;

INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('nephrolithiasis', 'DOID:585');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('constipation', 'DOID:2089');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Crohn''s disease', 'DOID:8778');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('bloodstream infections in pediatric oncology  populations', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('frail elderly', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('asthma', 'DOID:2841');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('obesity', 'DOID:9970');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('autism spectrum disorder', 'DOID:0060041');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('cystic fibrosis', 'DOID:1485');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('anorexia nervosa', 'DOID:8689');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('gastritis', 'DOID:4029');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Sjogren''s syndrome', 'DOID:12894');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('graf-versus-host disease', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('food allergy', 'DOID:3044');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('epilepsy', 'DOID:1826');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('cardiometabolic disorders with improper levels of total cholesterol', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('cardiometabolic disorders with improper levels low-density lipoprotein cholesterol', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('type 2 diabetes mellitus', 'DOID:9352');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('thyroiditis', 'DOID:7166');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('familial GUCY2C diarrhea syndrome', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('gastrointestinal helminths infection', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('attention deficit hyperactivity disorder', 'DOID:1094');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('nonalcoholic fatty liver disease', 'DOID:0080208');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('dysentery', 'DOID:12384');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('cardiorespiratory fitness in premenopausal women', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('abdominal obesity-metabolic syndrome', 'DOID:0060611');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('colorectal cancer', 'DOID:9256');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Parkinson''s disease', 'DOID:14330');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('rheumatoid arthritis', 'DOID:7148');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('osteoarthritis', 'DOID:8398');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('incontinence', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('irritable bowel syndrome', 'DOID:9778');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('hyperthyroidism', 'DOID:7998');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('eczema', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('diverticulitis of colon', 'DOID:13254');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('chronic obstructive pulmonary disease', 'DOID:3083');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('coeliac disease', 'DOID:10608');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('cholelithiasis', 'DOID:10211');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('allergic hypersensitivity disease', 'DOID:1205');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('acne', 'DOID:6543');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('liver cirrhosis', 'DOID:5082');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('ulcerative colitis', 'DOID:8577');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('atopic dermatitis', 'DOID:3310');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('hepatitis B virus-related decompensated cirrhosis', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('hepatitis B cirrhosis', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('perinatal necrotizing enterocolitis', 'DOID:8677');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('diarrhea', 'DOID:13250');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('acquired immunodeficiency syndrome', 'DOID:635');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('cholecystitis', 'DOID:1949');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('atherosclerosis', 'DOID:1936');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('iron-deficiency anaemia', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Helicobacter pylori infection', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('inflammatory bowel disease', 'DOID:0050589');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('gastroenteritis', 'DOID:2326');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('familial Mediterranean fever remission', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('familial Mediterranean fever attack', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('patients undergoing peritoneal dialysis', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('overweight', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('hypoglycemia', 'DOID:9993');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('microscopic colitis', 'DOID:0060182');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('microscopic colitis', 'DOID:0060183');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Clostridium difficile infection', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('multiple sclerosis', 'DOID:2377');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('colorectal carcinoma', 'DOID:0080199');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('primary sclerosing cholangitis', 'DOID:0060643');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('abdominal dysfunction', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('type 1 diabetes mellitus', 'DOID:9744');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Wilson disease', 'DOID:893');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('metabolic syndrome', 'DOID:0060611');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('autoimmune liver disease', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('keratitis', 'DOID:4677');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('gestational diabetes', 'DOID:11714');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('recurrent idiopathic calcium stone', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('pancreatic head cancer', 'DOID:1793');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('acute anterior uveitis', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Henoch-Schoenlein purpura', 'DOID:11123');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('celiac disease', 'DOID:10608');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('preterm neonate', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('acute pancreatitis', 'DOID:2913');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('colitis', 'DOID:0060180');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('arthritis', 'DOID:848');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('critically ill', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('bipolar disorder', 'DOID:3312');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('familial adenomatous polyposis', 'DOID:0050424');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('end stage renal disease', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Hirschsprung''s Disease', 'DOID:10487');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('acute lymphoblastic leukemia', 'DOID:9552');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('obesity', 'DOID:9770');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('chronic fatigue syndrome', 'DOID:8544');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('phenylketonuria', 'DOID:9281');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('prostatitis', 'DOID:14654');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('active celiac disease', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('oedematous severe acute malnutrition', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('spinal cord injury', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('botulism', 'DOID:11976');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('acute enteric infection', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('autoimmune hepatitis', 'DOID:2048');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Schistosoma haematobium infection', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('bacterial sepsis', 'DOID:00400085');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('diarrhea and fatigue in patients undergoing pelvic cancer radiotherapy', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('allergic hypersensitivity disease', 'DOID:1025');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('changes in body fat content due to weight loss', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('systemic lupus erythematosus', 'DOID:9074');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('stomach carcinoma', 'DOID:5517');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('depression', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Hirschsprung''s disease', 'DOID:14087');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('gender', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('cholesterol gallstone', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('glucose intolerance', 'DOID:10603');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('preterm infant', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Norovirus infection', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Crohn''s disease,ulcerative colitis', 'DOID:8878,DOID:8577');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Rett syndrome', 'DOID:1206');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('head and neck squamous cell carcinoma', 'DOID:5520');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('human immunodeficiency virus infectious disease', 'DOID:526');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('breast cancer', 'DOID:1612');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('mediastinum neuroblastoma', 'DOID:10660');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('cardiore spiratory fitness', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('lactose intolerance', 'DOID:10604');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('polycystic ovary syndrome', 'DOID:11612');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('pre-eclampsia', 'DOID:10591');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('hepatic encephalopathy', 'DOID:13413');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('suspected infectious diarrhea', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('necrotizing enterocolitis', 'DOID:8677');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('acute myeloid leukemia', 'DOID:9119');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('acute myocardial infarction', 'DOID:9408');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('leukemia', 'DOID:12603');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('diabetes mellitus', 'DOID:9351');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('H. polygyrus infection', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('pyogenic liver abscess induced by Klebsiella pneumoniae', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('Alzheimer''s disease', 'DOID:10652');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('spontaneous chronic colitis', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('liver disease', 'DOID:409');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('pyrimidine metabolic disorder', 'DOID:0050832');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('ankylosing spondylitis', 'DOID:7147');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('obesity prone', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('diabetic state', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('delirium-like behaviors after abdominal surgery', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('diabetes mellitus', 'DOID:9357');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('alcoholic hepatitis', 'DOID:12351');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('aging', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('chronic nonbacterial prostatitis', 'DOID:14654');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('pulmonary arterial hypertension', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('phosphatase 6 deficiency', 'null');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES (' Emily Ho', ' Thomas J. Sharpton?');
INSERT INTO gutmdisorder.disorder (name, do_id) VALUES ('undernourishment', 'null');